# Generated by Django 5.1.3 on 2024-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='factory_year',
        ),
        migrations.AddField(
            model_name='car',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='kilometers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
